spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
