spring:
  profiles:
    group:
      dev:
        - oauth
        - h2
      prod:
        - oauth
        - prod
        - prod-db
    active: dev
  session:
    store-type: jdbc


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
