spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 443091072970-213s3rvbmp7lv20gh0rk4cn0o9i3iaj6.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            client-id: 4EFmd0pxFttHp1ulzg_S
            client-secret: XZc4GW26CU
            scope: name,email,profile_image
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response