spring:
  profiles:
    group:
      dev:
        - oauth
        - h2
      prod:
        - oauth
        - prod
        - prod-db
      prod1:
        - oauth
        - prod1
        - prod-db
      prod2:
        - oauth
        - prod2
        - prod-db
    active: dev
  session:
    store-type: jdbc
  pid:
    file: /home/ec2-user/app/step2/springboot-webservice.pid

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
